import { useEffect } from 'react';
import Head from 'next/head';
import { useWallet, useNFTLogin } from '../hooks';

export default function Home() {
  const { checkWalletIsConnected, currentAccount } = useWallet();

  const nftId = 5;
  const { checkNFTLogin, isAuthenticated } = useNFTLogin();

  useEffect(() => {
    checkWalletIsConnected();
  }, [checkWalletIsConnected]);

  useEffect(() => {
    if (currentAccount) {
      checkNFTLogin(currentAccount);
    }
  }, [currentAccount, checkNFTLogin]);

  return (
    <div>
      <Head>
        <title>NFT Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={{ padding: '24px' }}>
        <h1>NFT Page</h1>
        <p>Your Wallet: {currentAccount}</p>
        {isAuthenticated === true && (
          <p>Success: You have a authorized NFT！！！</p>
        )}
        {isAuthenticated === false && (
          <p>Error: You have not a authorized NFT.</p>
        )}
        {isAuthenticated === undefined && <p>Checking your NFT....</p>}
      </main>
    </div>
  );
}
