import { useEffect } from 'react';
import Head from 'next/head';
import { useWallet, useNFTLogin, useInvitation } from '../hooks';

export default function Home() {
  const { checkWalletIsConnected, currentAccount } = useWallet();

  const { checkNFTLogin, isAuthenticated } = useNFTLogin();

  const { addressToInvite, onChangeAddressToInvite, onSubmiteInvitationForm } =
    useInvitation();

  useEffect(() => {
    checkWalletIsConnected();
  }, [checkWalletIsConnected]);

  useEffect(() => {
    if (currentAccount) {
      checkNFTLogin(currentAccount);
    }
  }, [currentAccount, checkNFTLogin]);

  return (
    <div>
      <Head>
        <title>NFT Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={{ padding: '24px' }}>
        <h1>NFT Page</h1>
        <p>Your Wallet: {currentAccount}</p>
        {isAuthenticated === false && (
          <p>Error: You have not a authorized NFT.</p>
        )}
        {isAuthenticated === undefined && <p>Checking your NFT....</p>}
        {isAuthenticated === true && (
          <div>
            <p>Success: You have a authorized NFT！！！</p>
            <h2>Invitation Form</h2>
            <form onSubmit={onSubmiteInvitationForm}>
              <div>
                <label
                  htmlFor="addressToInvite"
                  style={{ display: 'flex', flexDirection: 'column' }}
                >
                  Address to invite
                  <input
                    id="addressToInvite"
                    name="addressToInvite"
                    type="text"
                    onChange={onChangeAddressToInvite}
                    value={addressToInvite}
                    style={{ margin: '8px 0 16px 0' }}
                  />
                </label>
              </div>
              <button type="submit">Submit</button>
            </form>
          </div>
        )}
      </main>
    </div>
  );
}
